// Generates sequential, human-readable reference numbers like "SAN-2026-00001",
// "APT-2026-00421", "INV-2026-01204". These are what get shown to hospital
// staff instead of MongoDB's hard-to-read internal ObjectIds.
//
// How the numbering works: a small "counters" collection keeps one document
// per (prefix, year) pair, and each new number is generated by having
// MongoDB increment that document's value with findOneAndUpdate + $inc. This
// avoids two requests ever getting handed the same number even if they ask
// for a new id for the same prefix at the same moment, because MongoDB
// processes each increment one at a time.

import { Schema, model } from 'mongoose'

// One document per "sequence" — e.g. { key: 'SAN-2026', value: 124 } means
// the last patient number issued this year was SAN-2026-00124.
const counterSchema = new Schema({
  key: { type: String, required: true, unique: true },
  value: { type: Number, required: true, default: 0 },
})

const Counter = model('Counter', counterSchema)

// Returns the next id for a given prefix, e.g. generateId('SAN') -> 'SAN-2026-00001'.
// `padLength` controls how many digits the running number is padded to with
// leading zeros (5 digits gives numbers like SAN-2026-00001).
export async function generateId(prefix: string, padLength = 5): Promise<string> {
  const year = new Date().getFullYear()
  const key = `${prefix}-${year}`

  // $inc increments the counter for this prefix+year combination as a single
  // database operation, creating it (via upsert) the first time it's used
  // each year, and returns the new value in the same round-trip. Doing the
  // read and update as one operation is what keeps two simultaneous requests
  // from ever getting the same number.
  const counter = await Counter.findOneAndUpdate(
    { key },
    { $inc: { value: 1 } },
    { upsert: true, returnDocument: 'after' },
  )

  const sequence = String(counter!.value).padStart(padLength, '0')
  return `${key}-${sequence}`
}
